apiVersion: v1
kind: Pod
metadata:
  name: hello-docker
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: hello-docker
      image: registry.cn-guangzhou.aliyuncs.com/hello_kubernetes/hello-docker:30c2b96
      ports:
        - containerPort: 8080
